#pragma once

const char* const KeyNames[] = {"Unknown",
								"Mouse 0",
								"Mouse 1",
								"Cancel",
								"Mouse 3",
								"Mouse 4",
								"Mouse 5",
								"Unknown",
								"Backspace",
								"Tab",
								"Unknown",
								"Unknown",
								"Clear",
								"Return",
								"Unknown",
								"Unknown",
								"Shift",
								"CTRL",
								"Alt",
								"Pause",
								"Caps Lock",
								"Kana",
								"Unknown",
								"Junja",
								"Final",
								"Kanji",
								"Unknown",
								"Esc",
								"Convert",
								"Nonconvert",
								"Accept",
								"Modechange",
								"Space",
								"Prior",
								"Pgdn",
								"End",
								"Home",
								"Left Arrow",
								"Up Arrow",
								"Right Arrow",
								"Down Arrow",
								"Select",
								"Print",
								"Execute",
								"Print Screen",
								"Insert",
								"Canc",
								"Help",
								"0",
								"1",
								"2",
								"3",
								"4",
								"5",
								"6",
								"7",
								"8",
								"9",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"A",
								"B",
								"C",
								"D",
								"E",
								"F",
								"G",
								"H",
								"I",
								"J",
								"K",
								"L",
								"M",
								"N",
								"O",
								"P",
								"Q",
								"R",
								"S",
								"T",
								"U",
								"V",
								"W",
								"X",
								"Y",
								"Z",
								"LWin",
								"RWin",
								"Apps",
								"Unknown",
								"Sleep",
								"Num0",
								"Num1",
								"Num2",
								"Num3",
								"Num4",
								"Num5",
								"Num6",
								"Num7",
								"Num8",
								"Num9",
								"Multiply",
								"Add",
								"Separator",
								"Subtract",
								"Decimal",
								"Divide",
								"F1",
								"F2",
								"F3",
								"F4",
								"F5",
								"F6",
								"F7",
								"F8",
								"F9",
								"F10",
								"F11",
								"F12",
								"F13",
								"F14",
								"F15",
								"F16",
								"F17",
								"F18",
								"F19",
								"F20",
								"F21",
								"F22",
								"F23",
								"F24",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Numlock",
								"ScrollLock",
								"VK_OEM_NEC_EQUAL",
								"VK_OEM_FJ_MASSHOU",
								"VK_OEM_FJ_TOUROKU",
								"VK_OEM_FJ_LOYA",
								"VK_OEM_FJ_ROYA",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"Unknown",
								"LShift",
								"RShift",
								"LCTRL",
								"RCTRL",
								"LAlt",
								"RAlt"};
const char* const priorities[] = {"Low", "Below Normal", "Normal", "Above Normal", "High"};
const char* const style[] = {"Number and text", "Number Only"};
const char* const positions[] = {"Top Right", "Top Left", "Bottom Right", "Bottom Left"};
const char* const items[] = {"Normal", "No Spikes", "No Hitbox", "No Solid", "Force Block", "Everything Hurts"};
const char* const trail[] = {"Normal", "Always Off", "Always On", "Inversed"};
const char* const fonts[] = {"Big Font", "Chat Font", "Font 01", "Font 02", "Font 03", "Font 04", "Font 05",
							 "Font 06",	 "Font 07",	  "Font 08", "Font 09", "Font 10", "Font 11", "Gold Font"};
const char* const rpc[] = {"Playing", "Editor", "Menu"};